icons_format = "{icon}"

[icons]
icons = "awesome4"

[[block]]
block = "github"
token = "your github token here (with notification access)"
format = " $icon $total.eng(w:1) "
info = ["total"]
warning = ["mention","review_requested"]
hide_if_total_is_zero = true

[[block]]
block = "docker"
interval = 2
format = " $icon $running/$total "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|ETH} via $device "

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"
full_format = "$icon $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "